staff_meeting/meeting_app/urls.py
from django.conf.urls import url
from meeting_app import views

app_name ='meeting_app'
urlpatterns=[
       url(r'^$',views.Create_MeetingListView.as_view(),name='list'),
       url(r'^register/$',views.register,name='register'),
       url(r'^user_login/$',views.user_login,name='user_login'),
       url(r'^create_meeting/$',views.Create_MeetingCreateView.as_view(),name='create_meeting'),
       url(r'^update/(?P<pk>\d+)/$',views.Create_MeetingUpdateView.as_view(),name='update'),
        url(r'^delete/(?P<pk>\d+)/$',views.Create_MeatingDeleteView.as_view(),name='delete'),
       url(r'^(?P<pk>\d+)/$',views.Create_MeetingDetailView.as_view(),name='meeting_detail'),
       url(r'^meeting_detail/$',views.meeting_detail,name='meeting_detail'),

       url(r'^member_list/$',views.Committee_MemberListView.as_view(),name='member_list'),

       url(r'^resulaton_list/$',views.ResulationListView.as_view(),name='resulaton_list'),
    



      # url(r'^$',views.Create_MeetingListView.as_view,name='list')
 ]

staff_meeting/staff_meeting/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from meeting_app import views
from django.conf import settings






urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^sendmail/',views.sendmail,name='sendmail'),
    url(r'^meeting_app/',include('meeting_app.urls', namespace='meeting_app')),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'special/',views.special,name='special'),


]

staff_meeting/meeting_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from datetime import datetime

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.PROTECT)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='static',blank=True)

    def __str__(self):
        return self.user.username

CHOICES = (
    ('Planning Meeting','Planning Meeting',),
    ('Exam Committee Meeting', 'Exam Committee Meeting'),
    ('Event Meeting','Event Meeting'),
    ('AC Meeting','AC Meeting'),
    ('General Meeting','General Meeting'),
    ('Other','Other')
)

class Create_Meeting(models.Model):
    #meeting_id = models.IntegerField()
    meeting_id = models.AutoField(primary_key=True)
    meeting_name= models.CharField(max_length=256, choices=CHOICES, default='General Meeting')
    meeting_sub= models.CharField(max_length=256)
    meeting_text= models.TextField(max_length=500)
    date = models.DateField(default=datetime.now)

    def __str__(self):
        return self.meeting_sub

    def get_absolute_url(self):
        return reverse("meeting_app:meeting_detail", kwargs={'pk': self.pk})

        #return reverse("meeting_app:meeting_detail")


class Committee_Member(models.Model):
    first_name = models.CharField(max_length=50,blank=False)
    last_name = models.CharField(max_length=50,blank=False)
    designation = models.CharField(max_length=50,blank=False)
    member_type = models.ForeignKey(Create_Meeting,related_name='committee_members')
    email = models.EmailField(max_length=70,blank=False)

    def __str__(self):
        return self.first_name


class Resulation(models.Model):
    resulaton_sub = models.ForeignKey(Create_Meeting, default= 'meeting_sub', related_name='resulations')
    agenda1=models.TextField(max_length=200)
    decision1 = models.TextField(max_length=200)
    agenda2 =models.TextField(max_length=200)
    decision2 = models.TextField(max_length=200)
    agenda3 =models.TextField(max_length=200)
    decision3 = models.TextField(max_length=200)
    agenda4 =models.TextField(max_length=200)
    decision4 = models.TextField(max_length=200)
    agenda5=models.TextField(max_length=200)
    decision5 = models.TextField(max_length=200)

    def __str__(self):
        return self.agenda1


# Create your models here.

staff_meeting/meeting_app/forms.py
from django import forms
from django.contrib.auth.models import User
from meeting_app.models import UserProfileInfo,Create_Meeting,Resulation





class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())


    class Meta():
        model = User
        fields = ('username','first_name','last_name','email','password')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')


class Create_MeetingForm(forms.ModelForm):
    class Meta():
        model = Create_Meeting
        fields =('meeting_name','meeting_sub','meeting_text','date')


class ResulationForm(forms.ModelForm):
    class Meta():
        model = Resulation
        fields=('resulaton_sub','agenda1','decision1','agenda2','decision2','agenda3','decision3','agenda4','decision4','agenda5','decision5')

staff_meeting/meeting_app/views.py
from django.shortcuts import render
from meeting_app.forms import UserForm,UserProfileInfoForm
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from . import models
from django.core.mail import send_mail
from django.conf import settings
from .forms import Create_MeetingForm







# Create your views here.
def index(request):
    return render(request,'meeting_app/index.html')

def sendmail(request):

    if request.method=='POST':
        message = request.POST['message']
        subject = request.POST['subject']
        email_from = settings.EMAIL_HOST_USER
        recipient_list = ['sohelsorowar@gmail.com','sohelsorowar@ru.ac.bd',13055417]
        #print('request', request.POST)
        #members = models.Committee_Member.objects.get(type=Committee_Member.email)
        #recipient_list = ['members',]
        #for member in members:
        #    recipient_list.append(member.email)


        send_mail( subject, message, email_from, recipient_list,fail_silently=False)
        return HttpResponse("Mail send successfully")








def create_meeting(request):
    return render(request,'meeting_app/create_meeting.html')

def meeting_detail(request):
    return render(request,'meeting_app/meeting_detail.html')



@login_required
def special(request):
    return HttpResponse("you are logged in !!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method =="POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)


        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']


            profile.save()

            registered = True
        else:
                print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'meeting_app/registration.html',
                               {'user_form':user_form,
                                'profile_form':profile_form,
                                 'registered':registered})






def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
                #return render(request,'meeting_app/create_meeting.html')
            else:
                return HttpResponse("Account not Active!!!")
        else:
            print("Someone tried to login and failed")
            print("Username: {} and password: {}".format(username,password))
            return HttpResponse("Invalied login!!")
    else:
        return render(request,'meeting_app/login.html',{})


class Create_MeetingListView(ListView):
    context_object_name = 'create_meetings'
    model = models.Create_Meeting

class Create_MeetingDetailView(DetailView):
    context_object_name = 'meeting_detail'
    model = models.Create_Meeting
    template_name = 'meeting_app/meeting_detail.html'

class Create_MeetingCreateView(CreateView):
    fields=('meeting_name','meeting_sub','meeting_text','date')
    model = models.Create_Meeting

class Create_MeetingUpdateView(UpdateView):
    fields=('meeting_name','meeting_sub','meeting_text','date')
    model = models.Create_Meeting


class Create_MeatingDeleteView(DeleteView):

    model = models.Create_Meeting
    success_url = reverse_lazy("meeting_app:list")


class Committee_MemberListView(ListView):
    context_object_name = 'committee_members'
    model = models.Committee_Member

# resulations

class ResulationListView(ListView):
        context_object_name = 'resulations'
        model = models.Resulation

#lass Create_MeetingListView(DetailView):
#    context_object_name='meeting_detail'
#    model = models.Create_Meeting
#    template_name = 'meeting_app/meeting_detail.html'

staff_meeting/templates/meeting_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
      <meta charset="utf-8">
      <!-- <title></title> -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

      <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
      <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->




  </head>
  <body >




  <nav class='navbar navbar-inverse navbar-static-top'>

      <div class="container">
        <ul class="nav navbar-nav">
            <!-- <li><a class=" navbar-link " href="{% url 'meeting_app:meeting_detail' %}">Meeting_Detail</a></li> -->

        <li><a class=" navbar-brand " >RU_Meeting</a></li>
          {% if user.is_authenticated %}
          <li><a class=" navbar-link " href="{% url 'index' %}">Home</a></li>
          <li><a class=" navbar-link " href="{% url 'admin:index' %}">Admin</a></li>

          <li><a class=" navbar-link " href="{% url 'meeting_app:create_meeting' %}">Create_Meeting</a></li>
          <li><a class=" navbar-link " href="{% url 'meeting_app:list' %}">Meeting_List</a></li>
          <li><a class=" navbar-link " href="{% url 'meeting_app:member_list' %}">Members</a></li>
          <li><a class=" navbar-link " href="{% url 'meeting_app:resulaton_list' %}">Resulation</a></li>

          <li><a class='navbar-link' href="{% url 'logout' %}">Logout</a></li>
          <li><a class='navbar-link' >User : {{ user.username }}</a></li>





          {% else %}
            <li><a class='navbar-link' href="{% url 'meeting_app:user_login' %}">Login</a></li>
            <li><a class=" navbar-link " href="{% url 'meeting_app:register' %}">Register</a></li>
          {% endif %}
        </ul>

                <ul class="nav navbar-nav navbar-right">
                         <li><input class="form-control mr-sm-2" type="text"  placeholder="Search"> </li>
                         <li> <button class="btn btn-#DCDCDC" type="submit" >Search</button> </li>

                </ul>
      </div>

    </nav>


    </div>
    </div>

    {% block body_block %}
    {% endblock %}

      <!-- {% load staticfiles %} -->

      <!-- <img src="{% static "{{user.profile_pic}}" %}" alt="{{ user.username }}" style=""> -->



  </body>


</html>

staff_meeting/templates/meeting_app/committee_member_list.html
{% extends 'meeting_app/base.html' %}
{% block body_block %}
<style>
  table, th, td {
    border: 4px solid white;
    border-collapse: collapse;
  }
  th, td {
    padding: 15px;
  }
</style>



<div class="mask rgba-gradient align-items-center" style=" background-color:#DCDCDC;">
<div class="container" >
<div class="jumbtron">
<h1>List of all Members</h1>

  <table style="width:100%">
  <tr>
    <th> <h3>first_name</h3>  </th>
    <th><h3>last_name</h3>  </th>
    <th><h3>designation</h3>  </th>
    <th><h3>type</h3>  </th>
    <th><h3>mail</h3>  </th>
  </tr>
  {% for committee_member in committee_members %}
  <tr>
    <th> {{ committee_member.first_name }}</th>
    <th> {{ committee_member.last_name }}</th>
    <th> {{ committee_member.designation }}</th>
    <th> {{ committee_member.member_type }}</th>
    <th> {{ committee_member.email }}</th>
  </tr>
  {% endfor %}
  </table>



</div>
</div>
</div>
{% endblock %}

staff_meeting/templates/meeting_app/create_meeting_confirm_delete.html
{% extends "meeting_app/base.html" %}
{% block body_block %}

<div class="mask rgba-gradient align-items-center" style=" background-color:#DCDCDC;">
<div class="container" >
<div class="jumbtron">
<h1>Delete {{create_meetings.meeting_name}}?</h1>
<form  method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'meeting_app:delete'  pk=meeting_detail.pk  %}">Cancel</a>
</form>
</div>
</div>
</div>
{% endblock %}

staff_meeting/templates/meeting_app/create_meeting_form.html
{% extends "meeting_app/base.html" %}
{% block body_block %}
{% load crispy_forms_tags %}

<div class="mask rgba-gradient align-items-center" style=" background-color:white;">
    <div class="container" >
        <div class="jumbtron">
          <h1>
           {% if not form.instance.pk %}
            CREATE MEETING
           {% else %}
           Update Create_Meeting
           {% endif %}
          </h1>

          <form method="post" novalidate>

                    {% csrf_token %}
                    <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                    {{ form.meeting_name|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                    {{ form.date|as_crispy_field }}
                    </div>
                   </div>


                     {{ form.meeting_sub|as_crispy_field }}

                     {{ form.meeting_text|as_crispy_field }}



                    <!-- {{ form|crispy }} -->

                    <input type="submit" class="btn btn-success"  value="Save">

          </form>






        </div>
    </div>
</div>

{% endblock %}

staff_meeting/templates/meeting_app/create_meeting_list.html
{% extends 'meeting_app/base.html' %}
{% block body_block %}
<style>
  table, th, td {
    border: 1px solid white;
    border-collapse: collapse;
  }
  th, td {
    padding: 15px;
  }
</style>



<div class="mask rgba-gradient align-items-center" style=" background-color:#DCDCDC;">
<div class="container" >
<div class="jumbtron">
<h1>List of Meetings.</h1>

  <table style="width:100%">
  <tr>
    <th> <h3>Meeting ID</h3>  </th>
    <th><h3>Meeting Type</h3>  </th>
    <th><h3>Meeting SubHeading</h3>  </th>
    <th><h3>Meeting Agenda</h3>  </th>
    <th><h3>Date</h3>  </th>
  </tr>
  {% for create_meeting in create_meetings %}
  <tr>
    <th> {{create_meeting.meeting_id }}</th>
    <th> {{ create_meeting.meeting_name }}</th>
    <th> <a href="{{create_meeting.meeting_id}}">{{ create_meeting.meeting_sub }}</a></th>
    <th> {{ create_meeting.meeting_text }}</th>
    <th> {{ create_meeting.date }}</th>
  </tr>
  {% endfor %}
  </table>



</div>
</div>
</div>
{% endblock %}

staff_meeting/templates/meeting_app/index.html
{% extends "meeting_app/base.html" %}
{% block body_block %}


<style>
  p {
  font-family: "Times New Roman", Times, serif;
}
img {
  display: block;
  margin-left: auto;
  margin-right: auto;
}
div.a {
  text-align: center;
  border-style: solid;
  border-color:#DCDCDC;
   color: #003d99 ;

  background-color:#DCDCDC	;
}
div.b {
  text-align: justify;
  border-style: solid;
  border-color:#DCDCDC;
   color: black ;

  background-color:white	;
}
img.b {
  float: left;
    border: 10px solid white;

}
h3.b{
text-align: left;
}
</style>

    <div class="mask rgba-gradient align-items-center" style=" background-color:white;">
        <div class="container" >
            <div class="jumbtron">
              <div class="a">
                <h1>University of Rajshahi</h1>
                <h4>Department of Computer Science and Engineering</h4>
                <img src="/static/logo.png" alt="" style="width:15%;height=15%;" >
              </div>

              <div class="b">

                <img class="b" src="/static/bkp.jpg" alt="" style="width:15%;height=15%;" >
                <h3 class="b">Chairman Message</h3>
                <p>The Department of Computer Science & Engineering (CSE), University of Rajshahi (RU), is one of the leading Graduate and Post-graduate department in Bangladesh. The curriculum offered by our department has been designed in accordance with different renowned universities around the world. Recently with financial aid from the World Bank and UGC worth 33 Million BDT, our department has been renovated to meet the highest standard of education and consequently, we now offer a world-class learning experience. All of our classrooms and laboratories are equipped with modern audio-visual teaching-learning facilities and necessary experimental kits for undergraduate and graduate students. At the same time, we have extended the facilities to enhance our research activities in different branches of computer science and its engineering applications. Moreover, we frequently arrange workshop, seminar, academic contest of students and extra-curriculum activities to explore the merits of our students in a different dimension. At the same time, we get our students involved in organizing these events to improve their leadership quality. We want our students to be capable of not in one dimension, but capable of multi-dimensions when they graduate. As a result, now our department is the right place for the students with dreams of becoming outstanding IT professionals and researchers. We are looking forward to welcome brilliant students.
                </p>
                <p>Thank you.</p>
                <p>Prof. Dr. Bimal Kumar Pramanik</p>

              </div>


                <h3>Staff Meeting and Notice </h3>
                <p>Here admin can call meeting automatically and decision can be save into databas.</p>
                <p>In this web app admin can send mail to the registerd members automatically or manually. </p>
                <p>After meeting decesion will be recorded to database so that admin can pull any data if necessary</p>


                <h3>Instructions</h3>
                <p>1. To add members click on admin and than click on Committee_members and than click on ADD COMMITTEE_MEMBEER+ on the top-right.</p>
                <p>2. To create meeting click on Create_Meeting. </p>
                <p>3. To see the list of meetings clik on Meeting_List.</p>
                <p>4. To update go to Meeting_List and click on Meeting_SubHeading(blue colored) and then update.</p>
                <p>5. To delete any meeting go to Admin than click on Create_Meeting and select the meeting you want to delete and press delete button on bottom-left.</p>
            </div>
        </div>
    </div>







{% endblock %}

staff_meeting/templates/meeting_app/login.html
{% extends 'meeting_app/base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}

<div class="mask rgba-gradient align-items-center" style=" background-color:white;">
    <div class="container" >

<div class="jumbtron">
  <h1>Log In to Continue</h1>
  <form action="{% url 'meeting_app:user_login' %}" method="post">
    {% csrf_token %}

    <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" name="username"  class="form-control" placeholder="Enter Username">
    </div>

    <div class="form-group">
          <label for="password">Password</label>
          <input type="password" class="form-control" name="password">
    </div>

    <input type="submit" class='btn btn-default'name="" value="Login">
    <h5>Don't have account? Click on register button</h5>
  </form>

</div>
</div>
</div>
{% endblock %}

staff_meeting/templates/meeting_app/meeting_detail.html
{% extends 'meeting_app/base.html' %}
{% block body_block %}




<div class="mask rgba-gradient align-items-center" style=" background-color:#DCDCDC;">
<div class="jumbtron">
  <div class="container">


    <form class="" action="{% url 'sendmail' %}" method="post">
      {% csrf_token %}
    <h1>Meeting Resulation/details page</h1>
    <p>ID : {{meeting_detail.meeting_id}}</p>
    <p>Type : {{meeting_detail.meeting_name}}</p>
    <p>SubHeadiing : {{meeting_detail.meeting_sub}}</p>
    <p>Agenda : {{meeting_detail.meeting_text}}</p>




    <p><a class='btn btn-warning' href="{% url 'meeting_app:update' pk=meeting_detail.pk %}">Update</a></p>


      <br>Mail Sub:</br>
      <input type="" name="subject" value="{{meeting_detail.meeting_sub}}" size="100">
      <br>Mail Text:</br>
      <input  type="" name="message" value="{{meeting_detail.meeting_text}}"  size="100" >

      <input type="submit" class="btn btn-success" name="" value="send mail" >

    </form>

  </div>

</div>
</div>
{% endblock %}

staff_meeting/templates/meeting_app/registration.html
{% extends "meeting_app/base.html" %}
{% load staticfiles %}
{% block body_block %}
{% load crispy_forms_tags %}

<div class="mask rgba-gradient align-items-center" style=" background-color:white;">
    <div class="container" >
        <div class="jumbtron">

  {% if registered %}
  <h1>Thankyou for registraing!!</h1>
  {% else %}
  <h2>REGISTER HERE </h2>

  <form method="post">
      {% csrf_token %}
       {{  user_form.username|as_crispy_field }}
       <div class="form-row">
         <div class="form-group col-md-6 mb-0">
           {{ user_form.first_name|as_crispy_field }}
         </div>
         <div class="form-group col-md-6 mb-0">
           {{ user_form.last_name|as_crispy_field }}
         </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6 mb-0">
          {{ user_form.email|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
          {{ user_form.password|as_crispy_field }}
        </div>
     </div>
          {{  profile_form.portfolio_site|as_crispy_field }}
          {{  profile_form.profile_pic|as_crispy_field }}
     <input type="submit" class="btn btn-success"name="" value="Register">


   </form>
{% endif  %}
</div>
</div>
</div>
{% endblock %}

staff_meeting/templates/meeting_app/resulation_list.html
{% extends 'meeting_app/base.html' %}
{% block body_block %}
<style>
  table, th, td {
    border: 4px solid white;
    border-collapse: collapse;
  }
  th, td {
    padding: 15px;
  }
</style>


<div class="mask rgba-gradient align-items-center" style=" background-color:#DCDCDC;">
<div class="container" >
<div class="jumbtron">
<h1>Resulations</h1>

  <table style="width:100%">
  <tr>
    <th> <h3>resulaton_sub</h3>  </th>
    <th> <h3>Agenda1</h3>  </th>
    <th><h3>decision1</h3>  </th>
    <th><h3>agenda2</h3>  </th>
    <th><h3>decision2</h3>  </th>
    <th> <h3>Agenda3</h3>  </th>
    <th><h3>decision3</h3>  </th>
    <th><h3>agenda4</h3>  </th>
    <th><h3>decision4</h3>  </th>
    <th> <h3>Agenda5</h3>  </th>
    <th><h3>decision5</h3>  </th>


  </tr>
  {% for resulation in resulations %}
  <tr>

    <th> <a href="{{resulation.resulation_id}}">{{ resulation.resulaton_sub }}</a></th>
    <th> {{ resulation.agenda1 }}</th>
    <th> {{ resulation.decision1 }}</th>
    <th> {{ resulation.agenda2 }}</th>
    <th> {{ resulation.decision2 }}</th>
    <th> {{ resulation.agenda3 }}</th>
    <th> {{ resulation.decision3 }}</th>
    <th> {{ resulation.agenda4 }}</th>
    <th> {{ resulation.decision4 }}</th>
    <th> {{ resulation.agenda5 }}</th>
    <th> {{ resulation.decision5 }}</th>
  </tr>
  {% endfor %}
  </table>



</div>
</div>
</div>
{% endblock %}